### ISSUE TITLE
Navigate through transactions in matching dialog

### ISSUE THREAD

**Issue by varac** [MoritzR/fints2ledger#12]
When matching transactions it would be nice to have an option for going back / undo if you accidentially entered a wrong account.
Similar to the [Buchhaltung matching dialog](https://github.com/dpaetzel/buchhaltung/blob/master/example_output/match.md) (i.e. back, skip, save and quit).

**Comment by varac** [comment]
Btw, sorry for creating so many issue, at some point I'm willing to contribute with PRs but right now I just want to track all issues/possible improvements. fints2ledger is super helpful for me so thanks for it !

**Comment by MoritzR** [comment]
No worries, I am glad you are reporting these issues :)
I will have a deeper look at the more complex ones eventually.

Regarding this issue:
You can use `Ctrl+C` to kill the program. I always use this in case I enter the wrong account. This works for me as I enter both the account and the purpose. If I mistype the account I abort before entering the purpose.
Once you have entered all the prompts, `fints2ledger` will have saved the transaction to the ledger file. Your best option then is to edit the ledger file using a text editor.
Does this work for your case?

There is also an option to skip a transaction. I tried to do a better job of documenting this here: https://github.com/MoritzR/fints2ledger/pull/14
