### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by varac** [MoritzR/fints2ledger#2]
Please support a permanent config file location, ideally under `~/.config/fints2ledger`.
Right now, fints2ledger creates a `config.yml` in every directory it's called.

**Comment by MoritzR** [comment]
This is a good idea! I will have a look at it

**Comment by MoritzR** [comment]
There is a new 0.5 version available https://pypi.org/project/fints2ledger/
The config files are now stored at `~/.config/fints2ledger` by default.

`journal.ledger` and `transactions.csv` are still stored in the current directory you run the command in, but you can use command line arguments to overwrite these defaults.

Can you check that this works for you?

**Comment by varac** [comment]
Ok, I'll give it a try. 
Btw, could you maybe git tag releases so it's transparent which commits end up in a pypi release ? Thanks !
And I wonder why the fints requirements are still `fints>=2,<3`, doesn't it work with latest fints ?
I'm asking because [fints has added PSD2 support](https://github.com/raphaelm/python-fints/commit/95079bc522a2905febe485cbdc2ed3d45c557c87) in v. `0.3.0`.

**Comment by varac** [comment]
Works, thx !
