### ISSUE TITLE
Bring back csv support

### ISSUE THREAD

**Issue by varac** [MoritzR/fints2ledger#27]
From https://github.com/MoritzR/fints2ledger/releases/tag/1.0.0: 

> There is no intermediate step anymore where all transactions are written to a csv file. This also means that importing from a csv file or exporting to a csv file is not supported anymore.

Thank you for your rewrite, I'm happy with current progress! 
But this is the only breaking change that holds me back from upgrading (and testing), because I have csv export/file creating in my work flow and would like to stick to it if possible. 
Is this sth what could get re-added without too much work ? If not I'll need to evaluate and change my current process.

**Comment by MoritzR** [comment]
> Is this sth what could get re-added without too much work ?

No this is not a problem.

Which of these options would you prefer?

1. the program writes the transactions to a csv file and then continues with the process of putting them into a ledger journal
2. the program writes the transactions to a csv file and then exits
3. whatever idea you have

**Comment by varac** [comment]
That's great !
I really liked the `--no-csv` and `--no-ledger` flags in the past.
My workflow was to first run `fints2ledger --no-ledger` to create the csv file, verify it, and then run `fints2ledger --no-csv` in a second step.

**Comment by MoritzR** [comment]
I have added two new flags in [version 1.1.0](https://github.com/MoritzR/fints2ledger/releases/tag/1.1.0).
They differ a bit from the previous tags but fit better with the current behavior of the app that no csv file is generated when no special flags for that are provided.

**Comment by varac** [comment]
Just started to test the new version, but got hold back by #8  (reopened).

**Comment by varac** [comment]
Works, I opened https://github.com/MoritzR/fints2ledger/issues/31 for a minor csv issue.

**Comment by varac** [comment]
Thanks !!
