### ISSUE TITLE
CSV files now have a ms-dos line ending

### ISSUE THREAD

**Issue by varac** [MoritzR/fints2ledger#31]
With the new version, csv files now have a ms-dos line ending. You can see it if you use `cat -A file.csv`, it shows at the end of each line: 

    ^M$

where the old version produced proper line endings:

    $

**Comment by varac** [comment]
Thanks ! As soon as there's a release I can test and verify it.

**Comment by MoritzR** [comment]
The fix is included in release [1.2.0](https://github.com/MoritzR/fints2ledger/releases/tag/1.2.0).
