### ISSUE TITLE
-0.01 EUR from CSV ends up as 1.0e-2 EUR

### ISSUE THREAD

**Issue by varac** [MoritzR/fints2ledger#32]
Edge case here: I have a CSV file with a transaction of `-0.01 EUR`. When I use fints2ledger to import it into my journal file the amount shows up as `1.0e-2 EUR`:)

**Comment by MoritzR** [comment]
Fixed the issue in release [1.2.0](https://github.com/MoritzR/fints2ledger/releases/tag/1.2.0).
